server:
  address: localhost
  port: 8083

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: ERROR

eureka:
  instance.hostname: localhost
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:h2:mem:cart;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2.console.enabled: true
  devtools:
    restart:
      enabled: true
  cloud:
    stream:
      default:
        contentType: application/*+avro
      bindings:
        order-events-in:
          destination: order-service-events
        user-management-events-in:
          destination: user-management-events
        cart-events-in:
          destination: cart-service-events
        cart-events-out:
          destination: cart-service-events
      kafka:
        binder:
          brokers: ${CONF_KAFKA_HOST:localhost}:${CONF_KAFKA_PORT:9092}
      schemaRegistryClient:
        endpoint: http://${CONF_SCHEMA_REGISTRY_HOST:localhost}:${CONF_SCHEMA_REGISTRY_PORT:8990}
  kafka:
    consumer:
      group-id: cart-group
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: ${CONF_KAFKA_HOST:localhost}:${CONF_KAFKA_PORT:9092}
cq-common:
  application-command-topic: application-command-topic
