server:
  address: localhost
  port: 8099

logging:
  file: ${spring.application.name}.log
  path: ../
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      enabled: true
  kafka:
    consumer:
      group-id: cq-shop
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: localhost:9092
  
cq-common:
  application-command-topic: application-command-topic
