server:
  address: localhost
  port: 8099

logging:
  path: ../
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      enabled: true
  kafka:
    consumer:
      group-id: cq-shop
      auto-offset-reset: earliest
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://localhost:8990
      default:
        contentType: application/*+avro
      user-management-events-in:
        destination: user-management-events
        contentType: application/*+avro
      user-management-events-out:
        destination: user-management-events
        contentType: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092
kafka:
  bootstrap:
    servers: localhost:9092
  
cq-common:
  application-command-topic: application-command-topic
