server:
  address: localhost
  port: 8082

logging:
  path: ../
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      enabled: true
  cloud:
    stream:
      default:
        contentType: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092
      schemaRegistryClient:
        endpoint: http://localhost:8990
      schema:
        avro:
          schema-locations: classpath:schemas/userManagementEvents.avsc,classpath:schemas/registerAccountCommand.avsc
  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: localhost:9092
cq-common:
  application-command-topic: application-command-topic
