server:
  address: localhost
  port: 8082

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
   
hystrix.command.default.execution.timeout.enabled: false
feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000

spring:
  devtools:
    restart:
      enabled: true
  cloud:
    stream:
      default:
        contentType: application/*+avro
      bindings:
        order-events-in:
          destination: order-service-events
        notification-service-events-in:
          destination: notification-service-events
        notification-service-events-out:
          destination: notification-service-events
        user-management-events-in:
          destination: user-management-events
      kafka:
        binder:
          brokers: ${CONF_KAFKA_HOST:localhost}:${CONF_KAFKA_PORT:9092}
      schemaRegistryClient:
        endpoint: http://${CONF_SCHEMA_REGISTRY_HOST:localhost}:${CONF_SCHEMA_REGISTRY_PORT:8990}
  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: ${CONF_KAFKA_HOST:localhost}:${CONF_KAFKA_PORT:9092}
cq-common:
  application-command-topic: application-command-topic
