server:
  address: localhost
  port: 8990

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      enabled: true
  kafka:
    consumer:
      group-id: cq-shop
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: ${CONF_KAFKA_HOST:localhost}:${CONF_KAFKA_PORT:9092}

cq-common:
  application-command-topic: application-command-topic
