server:
  address: localhost
  port: 8081

logging:
  file: ${spring.application.name}.log
  path: ../
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${CONF_EUREKA_HOST:127.0.0.1}:${CONF_EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:user-management;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          contentType: application/*+avro
          destination: user-management-events
        input:
          contentType: application/*+avro
          destination: user-management-events
        user-management-events-in:
          destination: user-management-events
          contentType: application/*+avro
        user-management-events-out:
          destination: user-management-events
          contentType: application/*+avro
      schemaRegistryClient:
        endpoint: http://localhost:8990
      schema:
        avro:
          schema-locations: classpath:schemas/UserCreatedEvent.avsc

  kafka:
    consumer:
      group-id: cq-shop
      auto-offset-reset: earliest
kafka:
  bootstrap:
    servers: localhost:9092
cq-common:
  application-command-topic: application-command-topic
